"""
Research Agent - Main Entry Point
Runs daily to find YouTube videos and download DOT documents
"""

import os
import sys
from datetime import datetime
import schedule
import time

import config
import youtube_scanner
import document_hunter
import kb_ingester


def generate_briefing(videos: list, documents: list = None) -> str:
    """
    Generate a daily briefing markdown file.

    Args:
        videos: List of video dicts from youtube_scanner
        documents: List of document paths from document_hunter

    Returns:
        Path to generated briefing file
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    time_str = datetime.now().strftime("%H:%M")

    # Create output directory if needed
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)

    filepath = os.path.join(config.OUTPUT_DIR, f"research-briefing-{date_str}.md")

    content = f"""# Research Briefing - {date_str}
Generated at {time_str}

## YouTube Discoveries

"""

    if videos:
        for i, video in enumerate(videos[:10], 1):
            content += f"""### {i}. {video['title']}
- **Channel:** {video['channel']}
- **Views:** {video['views']:,} | **Duration:** {video['duration']} min
- **URL:** {video['url']}
- **Search Query:** {video.get('query', 'N/A')}

"""
    else:
        content += "_No videos found matching criteria._\n\n"

    content += "## Downloaded Documents\n\n"

    if documents:
        for doc in documents:
            content += f"- {os.path.basename(doc)}\n"
    else:
        content += "_No new documents downloaded._\n\n"

    content += f"""
---
_Generated by Research Agent_
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Briefing saved to: {filepath}")
    return filepath


def run_research():
    """Execute the full research workflow"""
    print("=" * 60)
    print(f"Research Agent started at {datetime.now()}")
    print("=" * 60)

    # 1. YouTube scan
    print("\n[1/3] Scanning YouTube...")
    videos = youtube_scanner.scan_youtube(config.YOUTUBE_QUERIES)
    print(f"Found {len(videos)} relevant videos")

    # 2. Document hunt (can be slow, skip if needed)
    print("\n[2/3] Hunting documents...")
    documents = []
    # Uncomment to enable document hunting:
    # documents = document_hunter.hunt_documents(config.DOT_URLS)
    print(f"Downloaded {len(documents)} documents")

    # 3. Generate briefing
    print("\n[3/3] Generating briefing...")
    briefing_path = generate_briefing(videos, documents)

    # 4. Optional: Ingest to KB
    # if documents:
    #     print("\n[4/4] Ingesting to knowledge base...")
    #     stats = kb_ingester.ingest_to_kb(documents)
    #     print(f"Ingested: {stats}")

    print("\n" + "=" * 60)
    print("Research Agent complete")
    print("=" * 60)


def run_scheduled():
    """Run agent on schedule"""
    print(f"Research Agent scheduled for {config.RUN_TIME} daily")
    print("Press Ctrl+C to stop\n")

    schedule.every().day.at(config.RUN_TIME).do(run_research)

    while True:
        schedule.run_pending()
        time.sleep(60)


def main():
    """Main entry point"""
    if len(sys.argv) > 1:
        if sys.argv[1] == "--schedule":
            run_scheduled()
        elif sys.argv[1] == "--test":
            print("Running in test mode...")
            run_research()
        else:
            print("Usage: python research_agent.py [--schedule|--test]")
            print("  --schedule : Run on daily schedule")
            print("  --test     : Run once immediately")
    else:
        # Default: run once
        run_research()


if __name__ == "__main__":
    main()
