# GENERATE_INDEX.ps1
# Creates comprehensive table of contents for all Trajanus USA files

Write-Host ""
Write-Host "================================================================================" -ForegroundColor Cyan
Write-Host "TRAJANUS USA FILE INDEX GENERATOR" -ForegroundColor Cyan
Write-Host "================================================================================" -ForegroundColor Cyan
Write-Host ""

$rootPath = "G:\My Drive\00 - Trajanus USA"
$outputFile = "$rootPath\00-Command-Center\TRAJANUS_FILE_INDEX.md"

Write-Host "Scanning all files in Trajanus USA..." -ForegroundColor Yellow
Write-Host ""

# Get all files recursively
$allFiles = Get-ChildItem -Path $rootPath -Recurse -File -ErrorAction SilentlyContinue

Write-Host "Found $($allFiles.Count) files" -ForegroundColor Green
Write-Host "Generating index..." -ForegroundColor Yellow
Write-Host ""

# Group files by folder
$filesByFolder = $allFiles | Group-Object DirectoryName | Sort-Object Name

# Start building the markdown document
$markdown = @"
# TRAJANUS USA FILE INDEX
**Complete Table of Contents**
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Total Files: $($allFiles.Count)
Total Folders: $($filesByFolder.Count)

---

## QUICK SEARCH GUIDE

**Looking for...**
- Session summaries? → 07-Session-Journal/Session-Summaries/ or 08-EOS-Files/
- Technical details? → 07-Session-Journal/Technical-Journals/
- Personal reflections? → 07-Session-Journal/Personal-Diaries/
- Code from sessions? → 07-Session-Journal/Code-Repositories/
- Protocols? → 01-Core-Protocols/
- Scripts? → 00-Command-Center/
- Templates? → 10-Templates/ (if exists)
- Project files? → 09-Active-Projects/

---

## FILE STATISTICS

**By File Type:**
"@

# Count by extension
$extensions = $allFiles | Group-Object Extension | Sort-Object Count -Descending
foreach ($ext in $extensions) {
    $extName = if ($ext.Name) { $ext.Name } else { "(no extension)" }
    $markdown += "`n- **$extName**: $($ext.Count) files"
}

$markdown += "`n`n---`n`n"

# Add recent files section (last 7 days)
$recentCutoff = (Get-Date).AddDays(-7)
$recentFiles = $allFiles | Where-Object { $_.LastWriteTime -gt $recentCutoff } | Sort-Object LastWriteTime -Descending

if ($recentFiles.Count -gt 0) {
    $markdown += "## RECENT FILES (Last 7 Days)`n`n"
    $markdown += "**$($recentFiles.Count) files modified in last week:**`n`n"
    
    foreach ($file in $recentFiles | Select-Object -First 20) {
        $relPath = $file.FullName.Replace($rootPath + "\", "")
        $date = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm")
        $markdown += "- **$($file.Name)** - $date`n"
        $markdown += "  - Location: ``$relPath```n"
    }
    
    if ($recentFiles.Count -gt 20) {
        $markdown += "`n*...and $($recentFiles.Count - 20) more recent files*`n"
    }
    
    $markdown += "`n---`n`n"
}

# Add complete folder listing
$markdown += "## COMPLETE FOLDER STRUCTURE`n`n"

foreach ($folderGroup in $filesByFolder) {
    $folderName = Split-Path $folderGroup.Name -Leaf
    $relPath = $folderGroup.Name.Replace($rootPath, "").TrimStart("\")
    $fileCount = $folderGroup.Count
    
    $markdown += "### $relPath`n"
    $markdown += "**Files: $fileCount**`n`n"
    
    # Group files by type in this folder
    $fileTypes = $folderGroup.Group | Group-Object Extension
    
    foreach ($typeGroup in $fileTypes) {
        $extName = if ($typeGroup.Name) { $typeGroup.Name } else { "(no ext)" }
        $markdown += "**$extName ($($typeGroup.Count) files):**`n"
        
        foreach ($file in $typeGroup.Group | Sort-Object Name) {
            $size = if ($file.Length -lt 1KB) { 
                "$($file.Length) B" 
            } elseif ($file.Length -lt 1MB) { 
                "{0:N1} KB" -f ($file.Length / 1KB) 
            } else { 
                "{0:N1} MB" -f ($file.Length / 1MB) 
            }
            
            $date = $file.LastWriteTime.ToString("yyyy-MM-dd")
            $markdown += "- $($file.Name) ($size) - $date`n"
        }
        $markdown += "`n"
    }
    
    $markdown += "---`n`n"
}

# Add search tips at the end
$markdown += @"
## HOW TO USE THIS INDEX

### For Bill:
1. Press Ctrl+F to search for keywords
2. Look in the folder sections above
3. File paths show exact location

### For Claude:
1. Search this document in project knowledge
2. Use google_drive_search with specific terms
3. Reference folder paths in this index

---

## UPDATE THIS INDEX

To regenerate this index with current files:

``````powershell
cd "G:\My Drive\00 - Trajanus USA\00-Command-Center"
.\GENERATE_INDEX.ps1
``````

---

**Index generated by GENERATE_INDEX.ps1**
"@

# Write to file
$markdown | Out-File -FilePath $outputFile -Encoding UTF8

Write-Host "================================================================================" -ForegroundColor Green
Write-Host "INDEX COMPLETE" -ForegroundColor Green
Write-Host "================================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "File saved to:" -ForegroundColor Green
Write-Host "  $outputFile" -ForegroundColor White
Write-Host ""
Write-Host "Total files indexed: $($allFiles.Count)" -ForegroundColor Green
Write-Host "Total folders: $($filesByFolder.Count)" -ForegroundColor Green
Write-Host ""
Write-Host "You can now:" -ForegroundColor Cyan
Write-Host "  - Open the index file and press Ctrl+F to search" -ForegroundColor White
Write-Host "  - Ask Claude to search this index" -ForegroundColor White
Write-Host "  - Use SEARCH_FILES.ps1 for interactive search" -ForegroundColor White
Write-Host ""
